Allow setting extra component libraries at runtime
wgoossens/sopc2dts pull request #7
Opened 2018-12-01 16:37 UTC by expipiplus1

Closes #6

2018-12-03 21:45 UTC, wgoossens requested changes
Small style change request, but all in all very good.

2018-12-03 21:45 UTC, wgoossens commented on Sopc2DTS.java
Just a nitpick...
Could you rename 'extra-components' to 'extra-componentlibs'?
Here and in the lines below

2018-12-03 21:45 UTC, wgoossens commented on sopc2dts/lib/SopcComponentLib.java
>  	public SopcComponentDescription getScdByClassName(String className)
I like that refactured this to a new function instead of copy pasting.
Good Job.

2019-01-19 09:18 UTC, expipiplus1 commented
Sorry this took so long to resolve!

2019-01-28 15:34 UTC, merged

2019-01-28 15:34 UTC, wgoossens commented
Thank you for contributing!